apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoui-thymeleaf
  labels:
    app: todoui-thymeleaf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoui-thymeleaf
  template:
    metadata:
      labels:
        app: todoui-thymeleaf
    spec:
      containers:
        - name: todoui-thymeleaf
          image: <dein_registry>/todoui-thymeleaf:latest
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: todoui-thymeleaf
spec:
  selector:
    app: todoui-thymeleaf
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP
